### PR TITLE
Fix: Chrome connector fails to analize tmz.com

### LINKED ISSUE #387: Fix `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`
**Site:** `tmz.com`
**Connector:** CDP

**Stack:**

```
...
<--- Last few GCs --->

[45377:0x104000000]   647433 ms: Mark-sweep 1388.3 (1440.1) -> 1388.3 (1440.1) MB, 62.8 / 0.0 ms  allocation failure GC in old space requested
[45377:0x104000000]   647470 ms: Mark-sweep 1388.3 (1440.1) -> 1388.3 (1440.1) MB, 37.0 / 0.0 ms  allocation failure GC in old space requested
[45377:0x104000000]   647612 ms: Mark-sweep 1388.3 (1440.1) -> 1388.2 (1408.6) MB, 141.5 / 0.0 ms  last resort 
[45377:0x104000000]   647704 ms: Mark-sweep 1388.2 (1408.6) -> 1388.2 (1408.6) MB, 92.2 / 0.0 ms  last resort 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3f1bf02a9891 <JS Object>
    0: builtin exit frame: parse(this=0x3f1bf02997b1 <a JSON with map 0x233c2fb06039>,0x341edd802201 <Very long string[6153135]>)

    1: /* anonymous */ [/Users/alrra/projects/sonar/node_modules/chrome-remote-interface/lib/chrome.js:~264] [pc=0x20c8a1a88cf2](this=0x6a4e5fcc731 <an EventEmitter with map 0x269a62e44d01>,data=0x341edd802201 <Very long string[6153135]>)
    2: arguments adaptor fr...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 4: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 5: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqTwoByteString, unsigned short>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 6: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 7: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 8: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
 9: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
10: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
11: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
12: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
13: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
14: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
15: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
16: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
17: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
18: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
19: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
20: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
21: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
22: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
23: v8::internal::Handle<v8::internal::String> v8::internal::JsonParser<true>::SlowScanJsonString<v8::internal::SeqOneByteString, unsigned char>(v8::internal::Handle<v8::internal::String>, int, int) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
24: v8::internal::JsonParser<true>::ParseJsonValue() [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
25: v8::internal::JsonParser<true>::ParseJsonObject() [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
26: v8::internal::JsonParser<true>::ParseJsonValue() [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
27: v8::internal::JsonParser<true>::ParseJsonObject() [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
28: v8::internal::JsonParser<true>::ParseJsonValue() [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
29: v8::internal::JsonParser<true>::ParseJson() [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
30: v8::internal::Builtin_Impl_JsonParse(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/alrra/.nvm/versions/node/v8.1.3/bin/node]
31: 0x20c8a160415d
32: 0x20c8a1a88cf2
33: 0x20c8a160579b
```

### LINKED ISSUE #388: Fix `Cannot read property 'nodeName' of undefined
**Site:** msn.com
**Connector:** CDP

**Stack:**

```
...
  sonar:cli Failed to analyze: http://msn.com/ +2ms
  sonar:cli TypeError: Cannot read property 'nodeName' of undefined
  sonar:cli     at AsyncHTMLElement.get nodeName [as nodeName] (/Users/alrra/projects/sonar_/dist/src/lib/connectors/shared/async-html.js:108:33)
  sonar:cli     at Object.hasAttributeWithValue (/Users/alrra/projects/sonar_/dist/src/lib/utils/misc.js:110:28)
  sonar:cli     at CDPConnector.onResponseReceived (/Users/alrra/projects/sonar_/dist/src/lib/connectors/shared/remote-debugging-connector.js:233:20)
  sonar:cli     at <anonymous> +0ms
  sonar:connectors:shared:remote-debugging-connector Closing browsers used by CDP +0ms
  sonar:cli Total runtime: 12676ms +319ms
```

### LINKED ISSUE #471: tmz.com never fires onLoadEventFired on chrome
url: tmz.com
connector: chrome
problem: the `onLoadEventFired` nevers gets fired and thus the scan never ends.

This doesn't happen with `jsdom`.

Even though we have a `waitFor` timer, it used inside the event handler. It should be moved to the `collect` method.

### PR DESCRIPTION
**Pull request by molant**
Fix #387
Fix #388
Fix #471

### CODE REVIEW

**Comment by molant** [comment]
@sonarwhal/contributors I think this is ready to review. I've tried the connector with the sites that were giving us problems with different wait times and so far so good.

File: src/lib/connectors/shared/async-html.ts [hunk 1]
```diff
@@ -48,22 +53,43 @@ export class AsyncHTMLDocument implements IAsyncHTMLDocument {
...
+                // node = await this._DOM.describeNode({ nodeId });
+                // this._nodes.set(nodeId, node);
+            }
+        }
+
+        return nodes;
     }
 
     public async pageHTML(): Promise<string> {
+        if (this._outerHTML) {
```
Comment (sarvaje) [inline src/lib/connectors/shared/async-html.ts]: @molant I think we talk about this some time ago, but we can't cache the outherHTML, because it can change over time.

File: src/lib/connectors/shared/async-html.ts [hunk 2]
```diff
@@ -48,22 +53,43 @@ export class AsyncHTMLDocument implements IAsyncHTMLDocument {
...
+            const nodeId = nodeIds[i];
+            const node = this._nodes.get(nodeId);
+
+            if (node) {
+                nodes.push(new AsyncHTMLElement(node, this, this._DOM)); // eslint-disable-line no-use-before-define, typescript/no-use-before-define
+            } else {
+                // This node was added in the DOM and we don't have it cached
+                // TODO: uncomment once chrome 62 is released.
+                // See https://github.com/cyrus-and/chrome-remote-interface/issues/255 for more information
+                // node = await this._DOM.describeNode({ nodeId });
```
Comment (sarvaje) [inline src/lib/connectors/shared/async-html.ts]: Meanwhile the release chrome 62, I think a workaround can be call to `const { root: dom } = await this._DOM.getDocument({ depth: -1 });` and add to the cache the new elements.

File: src/lib/connectors/shared/remote-debugging-connector.ts [hunk 3]
```diff
@@ -186,12 +194,26 @@ export class Connector implements IConnector {
...
+                debug(`Error redirecting: ${requestUrl} is an infinite loop`);
+
+                return;
+            }
+
+            const hops = this._redirects.calculate(requestUrl);
+
+            // We limit the number of redirects
+            if (hops.length >= 10) {
+                return;
```
Comment (sarvaje) [inline src/lib/connectors/shared/remote-debugging-connector.ts]: Maybe we should warn to the user that something wrong is happening. The same things with the `debug` above

File: src/lib/connectors/shared/remote-debugging-connector.ts [hunk 4]
```diff
@@ -618,61 +670,81 @@ export class Connector implements IConnector {
...
-    /** Initiates all the process */
-    private onLoadEventFired(callback: Function): Function {
-        return () => {
-            const { DOM } = this._client;
-            const event: IEvent = { resource: this._finalHref };
+    /** Stops processing any network requests and returns once all the
+     * pending requests have been processed or `maxLoadWaitTime`,
+     * whichever happens first. */
+    // TODO: find a cleaner way of doing this
+    private waitForNetwork: Function = promisify((callback) => {
```
Comment (sarvaje) [inline src/lib/connectors/shared/remote-debugging-connector.ts]: IMO, it is more clear if you return a `new Promise` instead of promisify a function

File: src/lib/connectors/shared/async-html.ts (hunk 2 above)
Comment (molant) [reply src/lib/connectors/shared/async-html.ts]: @sarvaje and I spoke over the phone. For now we are going to leave as it is so we don't have to regenerate all the content for our Async Nodes. We might even leave it as it is in the future depending if this is a problem or not.

File: src/lib/connectors/shared/async-html.ts (hunk 1 above)
Comment (molant) [reply src/lib/connectors/shared/async-html.ts]: After talking with @sarvaje the new strategy is basically:
> The connector has waited enough time and sonar will scan the site as it is at that moment. If something changes while we are doing the analysis the user should increase the `waitFor` value.
