### PR TITLE
Fix: Filter out duplicate fetch requests in jsdom

### LINKED ISSUE #460: Same issue reported multiple times for the same resource on jsdom
**URL:** https://capitalone.com
**Connector:** jsdom
**Rule**: no-disallowed-headers

image

This doesn't reproduce with `cdp`

### PR DESCRIPTION
**Pull request by qzhou1607**
Fix #460

### CODE REVIEW

File: src/lib/connectors/jsdom/jsdom.ts [hunk 1]
```diff
@@ -77,6 +77,7 @@ class JSDOMConnector implements IConnector {
     private _manifestIsSpecified: boolean = false;
     private _window: Window;
     private _document: JSDOMAsyncHTMLDocument;
+    private _fetchedHrefs: Array<string>;
```
Comment (sarvaje) [inline src/lib/connectors/jsdom/jsdom.ts]: I think this is perfect for a `Set` instead of an array.

Comment (qzhou1607) [reply src/lib/connectors/jsdom/jsdom.ts]: @sarvaje Fixed.
