### PR TITLE
Fix: SyntaxError when using jsdom

### LINKED ISSUE #404: SyntaxError when using jsdom
Got this error when running sonar on `https://www.google.com`. The connector used was `jsdom`. This only happened when using `jsdom`.
```
/ Traversing the DOMSyntaxError
    at DocumentImpl.<anonymous> (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\living\nodes\ParentNode-impl.js:76:11)
    at DocumentImpl.querySelectorAll (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\utils.js:113:45)
    at Document.querySelectorAll (C:\github\Sonar.git\node_modules\jsdom\lib\jsdom\living\generated\ParentNode.js:52:45)
    at JSDOMAsyncHTMLDocument.querySelectorAll (C:\github\Sonar.git\dist\src\lib\connectors\jsdom\jsdom-async-html.js:12:68)
    at exports.findElementLocation (C:\github\Sonar.git\dist\src\lib\utils\location-helpers.js:45:50)
    at <anonymous>
- https://apis.google.com … ERAt_Iw/cb=gapi.loaded_0 downloaded
```

### PR DESCRIPTION
**Pull request by sarvaje**
Escape character `'` in selectors in location-helpers.ts
Fix #404

### CODE REVIEW

File: src/lib/utils/location-helpers.ts [hunk 1]
```diff
@@ -4,6 +4,15 @@ import { IAsyncHTMLAttribute, IAsyncHTMLElement, IProblemLocation } from './../t
 const debug: debug.IDebugger = d(__filename);
 
 const doubleQuotesRegex: RegExp = /"/g;
+const singleQuotesRegex: RegExp = /'/g;
```
Comment (molant) [inline src/lib/utils/location-helpers.ts]: Can't we have just a single regexp and do the change at once?

**Comment by sarvaje** [comment]
@molant done! I've also added a test.
