### PR TITLE
Fix: Reduce `timeout` for requests

### LINKED ISSUE #585: www.msn.com takes a long time to load using jsdom
Please tell us about your:

## Environment

* __`sonar` version__: 0.10.2
* __`Node.js` version__: 8.7.0
* __`npm` version__: 5.5.1

## `sonar` configuration

<details>
<summary>sonar's configuration</summary>

```json
{
    "connector": {
        "name": "jsdom",
        "options": {
            "waitFor": 1000
        }
    },
    "formatters": "stylish",
    "rulesTimeout": 120000,
    "rules": {
        "amp-validator": "off",
        "apple-touch-icons": "warning",
        "axe": "warning",
        "content-type": "warning",
        "disown-opener": "warning",
        "highest-available-document-mode": "warning",
        "html-checker": "warning",
        "manifest-exists": "warning",
        "manifest-file-extension": "warning",
        "manifest-is-valid": "warning",
        "meta-charset-utf-8": "warning",
        "no-disallowed-headers": "warning",
        "no-friendly-error-pages": "warning",
        "no-html-only-headers": "warning",
        "no-protocol-relative-urls": "warning",
        "no-vulnerable-javascript-libraries": "warning",
        "ssllabs": "off",
        "strict-transport-security": "warning",
        "x-content-type-options": "warning",
        "validate-set-cookie-header": "warning"
    }
}

```
</details>

## URL for which `sonar` failed

* __URL:__ https://www.msn.com

## Output

sonar takes forever to download certain resources like `Downloading https://static-global-s … /hp-wus/sc/2b/a5ea21.ico`

We might have to review our timeout policy.

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [X] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonar)
- [X] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

For non-trivial changes, please make sure you also:

- [ ] Added/Updated related documentation.
- [ ] Added/Updated related tests.

## Short description of the change(s)

Change the timeout from 30 seconds to 10 when using `requester`

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Fix #585

### CODE REVIEW

File: src/lib/connectors/utils/requester.ts [hunk 1]
```diff
@@ -28,11 +28,11 @@ const defaults = {
         'Cache-Control': 'no-cache',
         DNT: 1,
         Pragma: 'no-cache',
-        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'
+        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.2924.87 Safari/537.36'
```
Comment (alrra) [inline src/lib/connectors/utils/requester.ts]: Is there a way to remove the need to update this?

Comment (molant) [reply src/lib/connectors/utils/requester.ts]: Maybe we could add something in the release script? Also I think we should add another token for sonar with the current version. Something like `sonarwhal/0.14.1` or similar.

Comment (molant) [reply src/lib/connectors/utils/requester.ts]: Updated the list of tasks of #476

Comment (alrra) [reply src/lib/connectors/utils/requester.ts]: > Maybe we could add something in the release script?

Sure.

> Also I think we should add another token for sonar with the current version

I don't know what you are referring to?

Comment (molant) [reply src/lib/connectors/utils/requester.ts]: > I don't know what you are referring to?

Add `sonarwhal/0.14.1` to the user agent string

Comment (alrra) [reply src/lib/connectors/utils/requester.ts]: > Add sonarwhal/0.14.1 to the user agent string

Why do you want to do that?

Comment (molant) [reply src/lib/connectors/utils/requester.ts]: Because we should probably identify ourselves somehow?

Comment (alrra) [reply src/lib/connectors/utils/requester.ts]: Would that create problems at some point because of sniffing?

Personally I think that, where we don't want to check if servers are sniffing, we shouldn't go with the default so to get the most "accurate" results as possible.

Comment (molant) [reply src/lib/connectors/utils/requester.ts]: OK
